name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write


jobs:
  terraform-checks:
    runs-on: ubuntu-latest

    env:
        TF_VAR_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDUMMYKEYFORCIVALIDATIONONLY terraform-ci"

    strategy:
      matrix:
        environment:
          - dev
          - staging
          - prod

    defaults:
      run:
        working-directory: environments/${{ matrix.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::789655958476:role/terraform-github-actions
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Terraform Format Check
        run: terraform fmt -check -recursive ../..

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config=backend.hcl

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan